import  { BABYLIGHTS, COLOR_BASE_CON_ACLARACION, COLOR_BASE_SIN_ACLARACION, ILUMINACIONES_HIGHLIGHT_BALAYAGE } from "./color"
import { CORTE_DE_FORMA, CORTE_DE_FORMA_BABY, CORTE_DE_PUNTAS } from "./cortes"

export const ALL_SERVICE = [
  COLOR_BASE_CON_ACLARACION,
  CORTE_DE_FORMA,
  ILUMINACIONES_HIGHLIGHT_BALAYAGE,
  COLOR_BASE_SIN_ACLARACION,
  BABYLIGHTS,
  CORTE_DE_PUNTAS,
  CORTE_DE_FORMA_BABY,
]