import {
  BABYLIGHTS,
  COLOR_BASE,
  COLOR_BASE_SIN_ACLARACION,
  ILUMINACIONES_HIGHLIGHT_BALAYAGE,
} from "./color";
import { CORTE_DE_FORMA, CORTE_DE_FORMA_BABY, CORTE_DE_PUNTAS } from "./cortes";
import { TRATAMIENTO_PROFUNDO } from "./tratamientos";
import {
  CITA_DE_DEFINICION,
  CITA_EN_TRANSICION_CAPILAR,
  CITA_DEFINICION_INFANTIL,
} from "./citas";

import {
  RITUAL_INFANTIL,
  RITUAL_HIDRATANTE,
  RITUAL_REPARADOR,
} from "./rituales";

export const ALL_SERVICE = [
  COLOR_BASE,
  CORTE_DE_FORMA,
  ILUMINACIONES_HIGHLIGHT_BALAYAGE,
  COLOR_BASE_SIN_ACLARACION,
  BABYLIGHTS,
  CORTE_DE_PUNTAS,
  CORTE_DE_FORMA_BABY,
  TRATAMIENTO_PROFUNDO,
  CITA_DE_DEFINICION,
  CITA_EN_TRANSICION_CAPILAR,
  CITA_DEFINICION_INFANTIL,
  RITUAL_INFANTIL,
  RITUAL_HIDRATANTE,
  RITUAL_REPARADOR,
];
